### ISSUE TITLE
Incorrectly identifying RSpec testing suite

### ISSUE THREAD

**Issue by carlosramireziii** [jstorimer/spin#14]
I am seeing the following error in my Rails 3.0.9 project:

`no such file to load -- rspec/autorun (LoadError)`

The issue originates from line 85 in `spin.rb`:

`if defined?(RSpec)`

My project is not using RSpec itself, but is using the [rspec-expectations](https://github.com/rspec/rspec-expectations) gem in conjunction with Test::Unit.

Is there some other way of testing for an RSpec testing suite. Perhaps it should be an explicit option when the spin server is started?

**Comment by jstorimer** [comment]
There is an explicit option to force RSpec to be used, perhaps we need the same thing for `test/unit`?

**Comment by carlosramireziii** [comment]
Yes that would work.
