### ISSUE TITLE
Does it work with RSpec?

### ISSUE THREAD

**Issue by sgruhier** [jstorimer/spin#2]
I have an error but before sharing it just wanted to be sure that RSpec is compatible with spin

**Comment by jstorimer** [comment]
I haven't tested spin with RSpec. Please share.

**Comment by sgruhier** [comment]
I just did a spin serve
and spin push spec/models/user_spec.rb

And I  got
 `require': no such file to load -- spec_helper (LoadError)

**Comment by jstorimer** [comment]
Sounds like the same issue as #1

**Comment by tjh** [comment]
@sgruhler, how are you requiring spec_helper? We use:

```
require 'spec/spec_helper'
```

...in all our test files, regardless of it's location within the spec folder or how deep it's nested.

**Comment by tjh** [comment]
I did not have the same error with rspec (2.6.0) as sgruhler. It just doesn't run any tests:

```
Loading spec/models/version_spec.rb
Loaded suite /Users/tharvey/.rvm/gems/ree-1.8.7-2011.03@viper/bin/spin
Started

Finished in 0.000132 seconds.

0 tests, 0 assertions, 0 failures, 0 errors
```

I'm thrilled at your work on spin as Spork has been a source of frustration due to the reasons you mention in the README.

**Comment by sgruhier** [comment]
my rrequire is 

require 'spec_helper'

(rspec 2.6.0 too)

**Comment by aka47** [comment]
some with me, just does not runs any specs ...

**Comment by jstorimer** [comment]
Version 0.1.1 should be compatible with rspec2. I confirmed that it fixes both problems (missing spec_helper and missing output).

**Comment by sgruhier** [comment]
thanks!
it works

**Comment by tjh** [comment]
Thanks @jstorimer! Works nicely.
