### ISSUE TITLE
Spin loading, but not running test

### ISSUE THREAD

**Issue by sprad** [jstorimer/spin#24]
I can get the spin server running and attempting to run tests, but it seems to just hang for me:

Terminal 1

jspradlin:~/code/opower_workspace/jonesy [git: spin] $ spin serve -Itest
Preloaded Rails env in 8.29096007347107s...

Loading ["test/unit/relationship_test.rb"]

Terminal 2

jspradlin:~/code/opower_workspace/jonesy [git: spin] $ spin push test/unit/relationship_test.rb
Spinning up test/unit/relationship_test.rb

Platform:  Snow Leopard
test-unit (2.4.2)
ruby 1.9.2p290
rails (3.0.9)

**Comment by jstorimer** [comment]
So are you using the 'test-unit' gem specifically? Rather than just the one that comes with the std lib.

**Comment by sprad** [comment]
Hi Jesse,
Yes, the 'test-unit' gem is included specifically in our project's Gemfile.  Does this make a difference?

I forked the gem last night and put some debugging statements into the "spin" file.  Nothing unexpected occurred (i.e there were no exceptions thrown and all lines seemed to be executed).

Thanks in advance for any help you are able to provide.

**Comment by jstorimer** [comment]
I tried it on one of my apps with test-unit (2.4.2) and was unable to reproduce the issue. Can you provide a simple app that displays your problem?

**Comment by sprad** [comment]
I created a brand new rails application and was able to run the tests using spin without any problems.  I think it's safe to assume there is something wrong with the way my current project is set up.  This ticket can be closed.  I'll report back if I figure out what my environment specific issues are.  Thank you for all of your help.
