### ISSUE TITLE
Using spin to test a Rails Engine

### ISSUE THREAD

**Issue by uhlenbrock** [jstorimer/spin#31]
Best practice for testing Rails Engines seems to be placing a dummy app inside the test directory. I would love to use Spin to speed up my Engine tests, but the path to application.rb is hard-coded in the serve method. A CLI variable to override that value should allow me to use spin in this configuration.

**Comment by jstorimer** [comment]
I'm working on a new release that will allow custom preloading behaviour, perfect for your needs.

**Comment by uhlenbrock** [comment]
Great, thanks for the update!

**Comment by uhlenbrock** [comment]
I was able to get this working by passing the following argument `--preload test/dummy/config/application.rb`
