### ISSUE TITLE
[Feature] Collect 'time' to run the test

### ISSUE THREAD

**Issue by andhapp** [jstorimer/spin#38]
It would be nice to collect the time it takes to run specs through the 'push' command. However, the collection should be done after the tests have finished running. 

It might sound silly and I know any CI server would accomplish the same, but I am throwing it out there for some community bashing.

**Comment by aspiers** [comment]
Isn't this done now?  `spin serve --time`?

**Comment by kirs** [comment]
@andhapp can be closed?

**Comment by andhapp** [comment]
@kirs Yes. This can be closed. I can't remember what my initial thoughts were about this when I opened it, as it's been a while.
