### ISSUE TITLE
Errno::ENOENT when `spin push` while `spin serve` hasn't started yet 

### ISSUE THREAD

**Issue by dkoprov** [jstorimer/spin#42]
After update to the latest version of spin, when I forgot to serve up spin, I get an error `spin/bin/spin:249:in initialize: No such file or directory ... (Errno::ENOENT)` instead of the message: `Connection was refused. Have you started up spine serve yet?`

I've fixed this issue, but can't pull request it, because I already have a open pull request and github is suggesting me to put commits together.

**Comment by jstorimer** [comment]
:(

I just merged your other PR, can you submit it now? FYI github will allow multiple open PRs if they come from different named branches.

**Comment by dkoprov** [comment]
@jstorimer , I'm sorry for the spam in the issues. I'm not expiriensed with github yet. I've fixed this issue in the attached pull request. When it's done, I'll delete the #43 issue. It's the same as this one.

**Comment by jstorimer** [comment]
Closed by #43.
