### ISSUE TITLE
Error raised when non-existent files are passed

### ISSUE THREAD

**Issue by Slotos** [jstorimer/spin#47]
When non-existent files are passed files_to_load get populated with nil's. It seems accounted for but the corresponding line of code doesn't work due to either past refactoring or typo.

https://github.com/jstorimer/spin/blob/master/bin/spin#L233

``` ruby
end.compact.uniq
```

should be

``` ruby
end

files_to_load = files_to_load.compact.uniq
```

or

``` ruby
end

files_to_load.compact!
files_to_load.uniq!
```

`compact!` returns nil when there was nothing to compact, so `compact!.uniq!` chain doesn't work.

**Comment by jstorimer** [comment]
Fixed with #51.
