### ISSUE TITLE
empty -e argument from kicker not working

### ISSUE THREAD

**Issue by jkthorne** [jstorimer/spin#50]
kicker sends a -e '' that spin does not like.

has anyone come up with a solution between kicker and spin?

**Comment by matthuhiggins** [comment]
I've dealt with the same problem. It's two fold:
kicker doesn't need to add the -e '' thing. Maybe tell the owner of kicker to stop doing this.
spin does not handle a mix of parameters and file names. It thinks that -e and the blank string are file names.

I think this is a test/unit only problem, and I would also love to see this fixed.
