### ISSUE TITLE
Specifying the stream to output the test results

### ISSUE THREAD

**Issue by thedelchop** [jstorimer/spin#67]
I'm wondering out loud if there would be a way to get the test ouput to appear in the output stream of the `spin push` command as opposed to the output of the `spin serve` command. 

I'm happy to send in a pull request but I need a bit of help understand how the output streams work.  Is this even possible?

**Comment by thedelchop** [comment]
Ah is this the purpose of `push_results`?

**Comment by bittersweet** [comment]
yes `--push-results` provides what you want :-)

**Comment by thedelchop** [comment]
Thanks, :)
