### ISSUE TITLE
Reloading dependencies

### ISSUE THREAD

**Issue by fabiokr** [jstorimer/spin#87]
Any thoughts on how can I make spin reload dependencies that were loaded with "require_dependency"? I have tried a couple things without success:
- set cache_classes = false in the test env
- added before/after fork hooks with:

```
ActiveSupport::DescendantsTracker.clear
ActiveSupport::Dependencies.clear
ActionDispatch::Reloader.cleanup!
ActionDispatch::Reloader.prepare!
```

**Comment by kirs** [comment]
Which `require_dependency` do you mean?
