### ISSUE TITLE
Namespaced constants issue

### ISSUE THREAD

**Issue by fabiokr** [jstorimer/spin#88]
I using spin with rspec and a rails 3 application that contains namespaced controllers. Controllers that are not namespace run fine, but for namespaced ones I'm getting a `load_missing_constant` error.

```
[Spin] Loading ["spec/controllers/api/users_controller_spec.rb:1"] 
~/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activesupport-3.2.14/lib/
active_support/dependencies.rb:503:in `load_missing_constant': Expected ~/app/controllers/api/users_controller.rb to define Api::UsersController (LoadError)
```

Any ideas?

**Comment by kirs** [comment]
Could you share content of `app/controllers/api/users_controller.rb`?

**Comment by fabiokr** [comment]
``` ruby
class Api::UsersController < ApplicationController
  respond_to :json

  # GET /users
  def index
  end
end

```

**Comment by kirs** [comment]
Controller looks fine and issue is weird.
Can I see any kind of demo app where the issue is being reproduced?

**Comment by fabiokr** [comment]
Nm, it was an issue with my environment setup, thanks!
